name: Build and Deploy Docker image

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master         # Push events on master branch

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker image
      run: |
        docker build -t crud-app .
      working-directory: ./src
    - name: Tag and Push image to ECR 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        $(aws ecr get-login --no-include-email --region us-east-2)
        docker tag crud-app:latest 714220470716.dkr.ecr.us-east-2.amazonaws.com/crud-app:$GITHUB_SHA
        docker push 714220470716.dkr.ecr.us-east-2.amazonaws.com/crud-app:$GITHUB_SHA
